name: Publish

on:
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ tixts8uREfD06d0nOADYM_3NjiSi_ML9AMWxS1zX }}
        env:
          CF_ACCOUNT_ID: ${{ 0634c690abd9c6871fc8a625af65c46a }}
